// ignore_for_file: file_names, camel_case_types, non_constant_identifier_names, constant_identifier_names

import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:builder_xx/store/MyGlobalStoreBase.dart';
import '/manager/MyTheme.dart';

class MySvgNames_e {
  static const String add_to = "add_to",
      addEmail = "addEmail",
      addition = "addtion",
      addSix = "addSix",
      add_circle_l = "add_circle_l",
      add_circle_d = "add_circle_d",
      add_rect_l = "add_rect_l",
      addMusic = "addMusic",
      bili = "bili",
      barrage_l = "barrage_l",
      barrage_d = "barrage_d",
      bottom = "bottom",
      camera_d = "camera_d",
      cancel = "cancel",
      cancelAll = "cancelAll",
      checkRect_d = "checkRect_d",
      checkRect_l = "checkRect_l",
      circleDashed = "circleDashed",
      circle_wave_l = "circle_wave_l",
      circle_wave_d = "circle_wave_d",
      colorful_d = "colorful_d",
      colorful_l = "colorful_l",
      comment = "comment",
      cube = "cube",
      cloudShare = "cloudShare",
      circle_dot = "circle_dot",
      circle_line = "circle_line",
      dotCircle = "dotCircle",
      desktop_d = "desktop_d",
      desktop_l = "desktop_l",
      download = "download",
      doubleUp = "doubleUp",
      doubleDown = "doubleDown",
      down_full = "down_full",
      disc = "disc",
      delete = "delete",
      error = "error",
      edit = "edit",
      editScreen_d = "editScreen_d",
      expand = "expand",
      eye_d = "eye_d",
      eye_l = "eye_l",
      exit = "exit",
      leave = "leave",
      folder = "folder",
      folderUp = "folderUp",
      face_l = "face_l",
      face_d = "face_d",
      github = "github",
      heart_d = "heart_d",
      heart_l = "heart_l",
      history_l = "history_l",
      history_d = "history_d",
      help = "help",
      home_d = "home_d",
      home_l = "home_l",
      info_d = "info_d",
      info_l = "info_l",
      key = "key",
      light_d = "light_d",
      like_d = "like_d",
      like_l = "like_l",
      location = "location",
      lock_d = "lock_d",
      lyric_d = "lyric_d",
      lyric_l = "lyric_l",
      list = "list",
      list2 = "list2",
      link = "link",
      love_d = "love_d",
      love_l = "love_l",
      language = "language",
      menu = "menu",
      menuLeft_d = "menuLeft_d",
      menuLeft_l = "menuLeft_l",
      menuRight_d = "menuRight_d",
      menuRight_l = "menuRight_l",
      MimicryMusic_full = "MimicryMusic-full",
      MimicryMusic_tran = "MimicryMusic-tran",
      mobile_d = "mobile_d",
      mobile_l = "mobile_l",
      mobileAi_d = "mobileAi_d",
      mobileAi_l = "mobileAi_l",
      moon_d = "moon_d",
      moon_l = "moon_l",
      moreBtn_d = "moreBtn_d",
      moreBtn_l = "moreBtn_l",
      multiple = "multiple",
      music = "music",
      page = "page",
      picture_d = "picture_d",
      plane_d = "plane_d",
      plane_l = "plane_l",
      playlist_d = "playlist_d",
      playlist_l = "playlist_l",
      pauseMedia = "pauseMedia",
      playMedia_hollow = "playMedia_hollow",
      playMedia = "playMedia",
      playOnly = "playOnly",
      playOrder = "playOrder",
      playRand = "playRand",
      pointDoubleLeft = "pointDoubleLeft",
      pointDoubleRight = "pointDoubleRight",
      pointDown = "pointDown",
      pointLeft_large = "pointLeft_large",
      pointLeft_mini = "pointLeft_mini",
      pointLeft2 = "pointLeft2",
      pointRight_large = "pointRight_large",
      pointRight = "pointRight",
      pointRight2 = "pointRight2",
      pointLeft_full_mini = "pointLeft_full_mini",
      pointRight_full = "pointRight_full",
      pointLeft_full = "pointLeft_full",
      pointUp = "pointUp",
      position = "position",
      palette = "palette",
      pin_l = "pin_l",
      pin_d = "pin_d",
      reduce = "reduce",
      refresh = "refresh",
      right = "right",
      ring = "ring",
      screenMask_l = "screenMask_l",
      screenMask_d = "screenMask_d",
      screenMask = "screenMask",
      search_l = "search_l",
      searchPage = "searchPage",
      select = "select",
      selectClock = "selectClock",
      setClocking = "setClocking",
      setting_d = "setting_d",
      setting_l = "setting_l",
      sort_alt = "sort_alt",
      sort_desc = "sort_desc",
      sort_name = "sort_name",
      sort_size = "sort_size",
      sort_time = "sort_time",
      sort = "sort",
      speed = "speed",
      stack_d = "stack_d",
      stack_l = "stack_l",
      star_d = "star_d",
      star_l = "star_l",
      star2_d = "star2_d",
      star2_l = "star2_l",
      share = "share",
      subtract = "subtract",
      subtract_circle = "subtract_circle",
      top = "top",
      thumbtask = "thumbtask",
      time = "time",
      timeCancle = "timeCancle",
      tip_d = "tip_d",
      tip_l = "tip_l",
      textSize = "textSize",
      upload = "upload",
      user_book_close = "user_book_close",
      user_book_open = "user_book_open",
      user_d = "user_d",
      user_l = "user_l",
      user_exit = "user_exit",
      userFollow_d = "userFollow_d",
      userHistory_d = "userHistory_d",
      userHistory_l = "userHistory_l",
      userSignIn = "userSignIn",
      userSignUp = "userSignUp",
      video_d = "video_d",
      volume_zero = "volume_zero",
      volume = "volume",
      warning = "warning";

  MySvgNames_e._();
}

class MySvgImgName_e {
  static const String addition = "addition",
      animate = "animate",
      audioWave = "audioWave",
      balloon = "balloon",
      bilibili = "bilibili",
      block = "block",
      back = "back",
      cancel = "cancel",
      clean = "clean",
      cloud = "cloud",
      clock = "clock",
      down = "down",
      download = "download",
      djmusic = "djmusic",
      delete = "delete",
      delete2 = "delete2",
      disable = "disable",
      light = "light",
      lyric = "lyric",
      lock = "lock",
      heart = "heart",
      hourglass = "hourglass",
      help = "help",
      key = "key",
      edit = "edit",
      exit = "exit",
      fullScreenExit = "fullScreenExit",
      fullScreenInto = "fullScreenInto",
      file = "file",
      folder = "folder",
      folderUp = "folderUp",
      info = "info",
      infinityLoop = "infinity-loop",
      infinity = "infinity",
      imgCloud = "imgCloud",
      imgMusical = "imgMusical",
      imgText = "imgText",
      imgTime = "imgTime",
      imgVip = "imgVip",
      musicIcon = "musicIcon",
      multi = "multi",
      music = "music",
      music2 = "music2",
      music3 = "music3",
      moon = "moon",
      more = "more",
      rate = "rate",
      right = "right",
      play = "play",
      playlist = "playlist",
      playlistIcon = "playlistIcon",
      painting = "painting",
      pointLeft = "pointLeft",
      pointRight = "pointRight",
      reset = "reset",
      reload = "reload",
      up = "up",
      home1 = "home_1",
      home2 = "home_2",
      home3 = "home_3",
      server = "server",
      search = "search",
      screen = "screen",
      sun = "sun",
      songIcon = "songIcon",
      song = "song",
      star = "star",
      star2 = "star2",
      setting = "setting",
      vip = "vip",
      target = "target",
      time = "time",
      theme = "theme",
      weather = "weather",
      wave = "wave",
      work = "work";

  MySvgImgName_e._();
}

class MySvg extends StatelessWidget {
  final String svgName;
  final double? size;
  final Color? color;
  final BoxFit fit;

  const MySvg({
    super.key,
    required this.svgName,
    this.size,
    this.color = MyColors_e.blue_tianyi,
    this.fit = BoxFit.contain,
  });

  @override
  Widget build(BuildContext context) {
    final size = this.size ?? 100.r;
    return SvgPicture.asset(
      "svg/$svgName.svg",
      width: size,
      height: size,
      colorFilter: ColorFilter.mode(
        color ?? MyColors_e.grey_lite,
        BlendMode.srcIn,
      ),
      fit: fit,
      clipBehavior: Clip.none,
    );
  }
}

class MySvgImage extends StatelessWidget {
  final String svgName;
  final double? size;
  final BoxFit fit;
  final bool? enableImageForegroundColor;

  const MySvgImage({
    super.key,
    required this.svgName,
    this.size,
    this.fit = BoxFit.contain,
    this.enableImageForegroundColor = false,
  });

  /// 填充满整个容器
  const MySvgImage.full({
    super.key,
    required this.svgName,
    this.size,
    this.enableImageForegroundColor = false,
  }) : fit = BoxFit.cover;

  @override
  Widget build(BuildContext context) {
    final theme_s = MyGlobalStoreBase.theme_s;
    final enableImageForegroundColor = this.enableImageForegroundColor ??
        theme_s.enableNightImageForegroundColor;
    return SvgPicture.asset(
      "svg/img/$svgName.svg",
      width: size,
      height: size,
      fit: fit,
      clipBehavior: Clip.none,
      colorFilter: (enableImageForegroundColor && theme_s.isNight())
          ? ColorFilter.mode(
              theme_s.imageForegroundColor ?? MyColors_e.black.withOpacity(0.5),
              BlendMode.srcATop,
            )
          : null,
    );
  }
}
